[project]
name = "machine-learning-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aldair Maquera", email = "harperafterhours@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.2",
    "notebook>=7.6.2",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
machine-learning-zoomcamp = "machine_learning_zoomcamp:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
